### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by 20chan** [phillyai/color-picker-proto#1]
- [ ] 보고있는 화면에서 색 뽑아내기
  - [x] 돋보기
    - [x] 커서 픽셀 강조
    - [ ] 돋보기 위치 마우스 바로 위로
- [ ] 칼라 피커
  - [ ] 컬러 정보
    - [x] RGB
    - [x] HSL
    - [x] CMYK
    - [ ] 명도/채도/대비/보색
- [ ] 캡처 화면 색 비율 분석
- [ ] 뽑아낸 색, 선택한 색 등 최근 사용 색 히스토리 및 색 값 들고 있게 해주기
  - [ ] 컬러 히스토리
  - [ ] 컬러 팔레트
    - [ ] 컬러 팔레트 공유
    - [ ] 컬러 팔레트 수정 기능
- [ ] 해당 색과 관련있는 색 보여주기 (명도 채도 대비 및 보색 등 유의미한거)
